spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:loggerdb;DB_CLOSE_DELAY=- 1;DB_CLOSE_ON_EXIT=FALSE
    username: giancarlo
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8085

properties:
  logger:
    name-log: Test Log
    file-path: D:\Desarrollo\2019\loggerTxt.log
    database-log: true
    file-log: true
    console-log: true
    message-log: true
    warning-log: true
    error-log: true
